FROM rocker/r-base:4.0.0

# Install required system libraries
RUN apt-get update && apt-get install -y \
    libssl-dev \
    libxml2-dev

# Just copy install.R over to install necessary R packages
COPY ./install.R /tmp/install.R
RUN R -f /tmp/install.R

